"use client";

import { useState, useCallback } from "react";
import { Download, Check } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

interface ExportButtonProps {
  data: {
    owner: string;
    repo: string;
    analysis: {
      what_it_does: string;
      execution_flow: string[];
      key_modules: { file: string; role: string; why_it_exists: string }[];
      blast_radius?: { file: string; dependents: number; warning: string }[];
      onboarding_guide: string[];
    };
  };
}

export default function ExportButton({ data }: ExportButtonProps) {
  const [isExported, setIsExported] = useState(false);

  // --- PRINCIPAL UPGRADE: Memoized to prevent unnecessary re-renders
  const handleExport = useCallback(() => {
    let md = `# CodeAutopsy Report: ${data.owner}/${data.repo}\n\n`;
    
    md += `## System Purpose\n${data.analysis.what_it_does}\n\n`;
    
    md += `## Execution Flow\n`;
    data.analysis.execution_flow.forEach((step: string, index: number) => {
      md += `${index + 1}. ${step}\n`;
    });
    md += `\n`;
    
    md += `## Key Modules\n`;
    data.analysis.key_modules.forEach((mod) => {
      md += `- **\`${mod.file.split('/').pop()}\`** (${mod.role}): ${mod.why_it_exists}\n`;
    });
    md += `\n`;
    
    if (data.analysis.blast_radius && data.analysis.blast_radius.length > 0) {
      md += `## Blast Radius (Critical Files)\n`;
      data.analysis.blast_radius.forEach((risk) => {
        md += `- **\`${risk.file.split('/').pop()}\`** (${risk.dependents} dependents): ${risk.warning}\n`;
      });
      md += `\n`;
    }
    
    md += `## Developer Onboarding Guide\n`;
    data.analysis.onboarding_guide.forEach((tip: string) => {
      md += `- ${tip}\n`;
    });
    md += `\n`;
    
    md += `---\n*Generated by CodeAutopsy*`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    
    a.href = url;
    a.download = `${data.repo}-autopsy.md`;
    document.body.appendChild(a);
    a.click();
    
    // Cleanup
    document.body.removeChild(a);
    URL.revokeObjectURL(url);

    // --- PRINCIPAL UPGRADE: Trigger Success Micro-Interaction
    setIsExported(true);
    setTimeout(() => setIsExported(false), 2000);
  }, [data]);

  return (
    <motion.button
      whileTap={{ scale: 0.95 }}
      onClick={handleExport}
      disabled={isExported}
      aria-label="Export Markdown Report"
      className={`flex items-center gap-2 px-4 py-2 rounded-lg border font-mono text-[10px] uppercase tracking-widest font-bold h-9 flex-shrink-0 transition-all duration-300 ${
        isExported 
          ? "bg-emerald-500/10 border-emerald-500/30 text-emerald-400 shadow-[0_0_15px_rgba(16,185,129,0.15)]" 
          : "bg-white/5 hover:bg-white/10 border-white/10 text-slate-300 hover:text-white"
      }`}
    >
      <AnimatePresence mode="wait" initial={false}>
        {isExported ? (
          <motion.div
            key="check"
            initial={{ opacity: 0, scale: 0.5, rotate: -90 }}
            animate={{ opacity: 1, scale: 1, rotate: 0 }}
            exit={{ opacity: 0, scale: 0.5, rotate: 90 }}
            transition={{ duration: 0.2 }}
            className="flex items-center gap-2"
          >
            <Check className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Exported</span>
          </motion.div>
        ) : (
          <motion.div
            key="download"
            initial={{ opacity: 0, scale: 0.5, rotate: 90 }}
            animate={{ opacity: 1, scale: 1, rotate: 0 }}
            exit={{ opacity: 0, scale: 0.5, rotate: -90 }}
            transition={{ duration: 0.2 }}
            className="flex items-center gap-2"
          >
            <Download className="w-3.5 h-3.5" />
            <span className="hidden sm:inline">Export .md</span>
          </motion.div>
        )}
      </AnimatePresence>
    </motion.button>
  );
}