"use client";

import { Download } from "lucide-react";

interface ExportButtonProps {
  data: {
    owner: string;
    repo: string;
    analysis: {
      what_it_does: string;
      execution_flow: string[];
      key_modules: { file: string; role: string; why_it_exists: string }[];
      blast_radius?: { file: string; dependents: number; warning: string }[];
      onboarding_guide: string[];
    };
  };
}

export default function ExportButton({ data }: ExportButtonProps) {
  const handleExport = () => {
    let md = `# CodeAutopsy Report: ${data.owner}/${data.repo}\n\n`;
    
    md += `## System Purpose\n${data.analysis.what_it_does}\n\n`;
    
    md += `## Execution Flow\n`;
    data.analysis.execution_flow.forEach((step: string, index: number) => {
      md += `${index + 1}. ${step}\n`;
    });
    md += `\n`;
    
    md += `## Key Modules\n`;
    data.analysis.key_modules.forEach((mod) => {
      md += `- **\`${mod.file.split('/').pop()}\`** (${mod.role}): ${mod.why_it_exists}\n`;
    });
    md += `\n`;
    
    if (data.analysis.blast_radius && data.analysis.blast_radius.length > 0) {
      md += `## Blast Radius (Critical Files)\n`;
      data.analysis.blast_radius.forEach((risk) => {
        md += `- **\`${risk.file.split('/').pop()}\`** (${risk.dependents} dependents): ${risk.warning}\n`;
      });
      md += `\n`;
    }
    
    md += `## Developer Onboarding Guide\n`;
    data.analysis.onboarding_guide.forEach((tip: string) => {
      md += `- ${tip}\n`;
    });
    md += `\n`;
    
    md += `---\n*Generated by CodeAutopsy*`;

    const blob = new Blob([md], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${data.repo}-autopsy.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <button
      onClick={handleExport}
      className="flex items-center gap-2 px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all font-mono text-[10px] uppercase tracking-widest font-bold h-9 flex-shrink-0"
    >
      <Download className="w-3.5 h-3.5" />
      <span className="hidden sm:inline">Export .md</span>
    </button>
  );
}