"use client";

import { submitDiagnosisFeedback } from "@/app/actions/feedback";
import { useState } from "react";
import {
  Check,
  Copy,
  Download,
  ThumbsUp,
  ThumbsDown,
  RotateCcw,
} from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";
import { CheckCircle2, Zap, AlertCircle, ArrowRight } from "lucide-react";

interface DebugResultsProps {
  result: {
    root_cause_hypothesis: string;
    fix_suggestions: string[];
    verification_steps: string[];
    confidence: "high" | "medium" | "low";
    requires_runtime_check: boolean;
    crash_node?: { file: string; line: number };
  };
  onReset: () => void;
}

export function DebugResults({ result, onReset }: DebugResultsProps) {
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<"up" | "down" | null>(null);
  const [hideFeedback, setHideFeedback] = useState(false);

  const confidenceColors = {
    high: "bg-green-500/10 border-green-500/20 text-green-400",
    medium: "bg-yellow-500/10 border-yellow-500/20 text-yellow-400",
    low: "bg-red-500/10 border-red-500/20 text-red-400",
  };

  const copyDiagnosis = () => {
    const text = `
CODE DOCTOR DIAGNOSIS
=====================

CONFIDENCE: ${result.confidence.toUpperCase()}

ROOT CAUSE:
${result.root_cause_hypothesis}

FIX SUGGESTIONS:
${result.fix_suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

VERIFICATION STEPS:
${result.verification_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

${result.requires_runtime_check ? "⚠️ This appears to be a runtime/state error. Check database, API, and environment variables." : ""}
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportMarkdown = () => {
    const markdown = `# Code Doctor Diagnosis

**Confidence:** ${result.confidence.toUpperCase()}  
**Crash Location:** \`${result.crash_node?.file}:${result.crash_node?.line}\`

## Root Cause Hypothesis

${result.root_cause_hypothesis}

${result.requires_runtime_check ? "> ⚠️ **Warning:** This appears to be a runtime/state error. Ensure you check database queries, API responses, and environment variables.\n" : ""}

## Fix Suggestions

${result.fix_suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Verification Steps

${result.verification_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

---
*Generated by CodeAutopsy Diagnostic Engine*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `diagnosis-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  const handleFeedback = async (type: "up" | "down") => {
    if (feedback !== null) return;

    setFeedback(type);

    setTimeout(() => {
      setHideFeedback(true);
    }, 2000);

    try {
      await submitDiagnosisFeedback(type === "up");
    } catch (error) {
      console.error("TELEMETRY_ERROR: Failed to log system accuracy", error);
    }
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-indigo-500/20 to-purple-500/20 border border-indigo-500/30 flex items-center justify-center">
            <span className="text-2xl">
              <Zap className="w-4 h-4 text-amber-400" />
            </span>
          </div>
          <div>
            <h3 className="text-lg font-bold text-white font-mono">
              Diagnostic Output
            </h3>
            <div
              className={`inline-flex items-center gap-2 px-3 py-1 rounded-md text-[10px] font-bold uppercase tracking-widest border font-mono mt-1 ${confidenceColors[result.confidence]}`}
            >
              {result.confidence}_CONFIDENCE
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          <button
            onClick={copyDiagnosis}
            title={copied ? "Copied diagnosis" : "Copy diagnosis"}
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm font-mono"
          >
            {copied ? (
              <Check className="w-4 h-4 text-green-400" />
            ) : (
              <Copy className="w-4 h-4" />
            )}
            {copied ? "COPIED" : "COPY"}
          </button>

          <button
            onClick={exportMarkdown}
            title="Export diagnosis as markdown"
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm font-mono"
          >
            <Download className="w-4 h-4" />
            EXPORT
          </button>

          <button
            onClick={onReset}
            title="Start new diagnosis"
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm font-mono"
          >
            <RotateCcw className="w-4 h-4" />
            NEW_SCAN
          </button>
        </div>
      </div>

      {result.requires_runtime_check && (
        <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 flex items-start gap-3">
          <span className="text-xl">⚠️</span>
          <div className="flex-1">
            <p className="text-sm text-yellow-200 font-medium mb-1 font-mono uppercase">
              Runtime_State_Warning
            </p>
            <p className="text-xs text-yellow-300/70">
              This appears to be a state or data error. Ensure you check your
              database, API endpoints, and environment variables.
            </p>
          </div>
        </div>
      )}

      {/* RED ALERT CRITICAL PATH DESIGN */}
      <div className="relative overflow-hidden rounded-xl border border-red-500/30 bg-gradient-to-br from-red-500/10 via-orange-500/5 to-transparent p-6 shadow-2xl shadow-red-900/20">
        <div className="absolute top-4 right-4 flex items-center gap-2">
          <span className="text-[10px] font-bold text-red-500 font-mono tracking-widest">
            CRITICAL_FAILURE
          </span>
          <div className="h-2 w-2 rounded-full bg-red-500 animate-ping" />
        </div>

        <h4 className="text-xs font-bold text-red-400 uppercase tracking-widest mb-3 font-mono">
          {">"} Root_Cause_Hypothesis
        </h4>
        <p className="text-slate-200 leading-relaxed font-medium text-lg">
          {result.root_cause_hypothesis}
        </p>
      </div>

      <div className="p-6 rounded-xl bg-white/[0.02] border border-white/10">
        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 font-mono">
          {">"} Fix_Suggestions
        </h4>
        <div className="space-y-3">
          {result.fix_suggestions.map((suggestion, i) => (
            <div key={i} className="flex gap-3">
              <div className="w-6 h-6 rounded-md bg-blue-500/10 border border-blue-500/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="text-xs text-blue-400 font-mono font-bold">
                  {i + 1}
                </span>
              </div>
              <p className="text-sm text-slate-300 leading-relaxed">
                {suggestion}
              </p>
            </div>
          ))}
        </div>
      </div>

      <div className="p-6 rounded-xl bg-white/[0.02] border border-white/10">
        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-4 font-mono">
          {">"} Verification_Steps
        </h4>
        <div className="space-y-3">
          {result.verification_steps.map((step, i) => (
            <div key={i} className="flex gap-3">
              <div className="w-6 h-6 rounded-md bg-green-500/10 border border-green-500/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="text-xs text-green-400 font-mono font-bold">
                  {i + 1}
                </span>
              </div>
              <p className="text-sm text-slate-300 leading-relaxed">{step}</p>
            </div>
          ))}
        </div>
      </div>

      <AnimatePresence mode="wait">
        {!hideFeedback && (
          <motion.div
            key={feedback ? "thanks" : "buttons"}
            initial={{ opacity: 0, y: 10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10, filter: "blur(4px)" }}
            className="flex flex-col items-center justify-center gap-4 pt-6 pb-2 border-t border-white/5 mt-8 flex-shrink-0"
          >
            {!feedback ? (
              <div className="flex items-center gap-4">
                <span className="text-[10px] text-slate-500 uppercase tracking-widest font-mono">
                  SYSTEM_ACCURACY_CHECK
                </span>
                <div className="flex gap-2">
                  <button
                    onClick={() => handleFeedback("up")}
                    aria-label="Mark feedback as helpful"
                    title="Mark feedback as helpful"
                    className="p-2 rounded-lg bg-white/5 border border-white/10 text-slate-400 hover:text-green-400 hover:bg-white/10 transition-all"
                  >
                    <ThumbsUp className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={() => handleFeedback("down")}
                    aria-label="Mark feedback as not helpful"
                    title="Mark feedback as not helpful"
                    className="p-2 rounded-lg bg-white/5 border border-white/10 text-slate-400 hover:text-red-400 hover:bg-white/10 transition-all"
                  >
                    <ThumbsDown className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            ) : (
              <div className="flex items-center gap-2 px-4 py-2 rounded-lg bg-green-500/10 border border-green-500/20">
                <CheckCircle2 className="w-4 h-4 text-green-400" />
                <span className="font-mono text-[10px] font-bold uppercase text-green-400 tracking-widest">
                  Feedback Recorded
                </span>
              </div>
            )}
          </motion.div>
        )}
      </AnimatePresence>
    </motion.div>
  );
}
