"use client";

import { useState } from "react";
import { Check, Copy, Download, ThumbsUp, ThumbsDown, RotateCcw } from "lucide-react";
import { motion } from "framer-motion";

interface DebugResultsProps {
  result: {
    root_cause_hypothesis: string;
    fix_suggestions: string[];
    verification_steps: string[];
    confidence: "high" | "medium" | "low";
    requires_runtime_check: boolean;
    crash_node?: { file: string; line: number };
  };
  onReset: () => void;
}

export function DebugResults({ result, onReset }: DebugResultsProps) {
  const [copied, setCopied] = useState(false);
  const [feedback, setFeedback] = useState<"up" | "down" | null>(null);

  const confidenceColors = {
    high: "bg-green-500/10 border-green-500/20 text-green-400",
    medium: "bg-yellow-500/10 border-yellow-500/20 text-yellow-400",
    low: "bg-red-500/10 border-red-500/20 text-red-400",
  };

  const copyDiagnosis = () => {
    const text = `
CODE DOCTOR DIAGNOSIS
=====================

CONFIDENCE: ${result.confidence.toUpperCase()}

ROOT CAUSE:
${result.root_cause_hypothesis}

FIX SUGGESTIONS:
${result.fix_suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

VERIFICATION STEPS:
${result.verification_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

${result.requires_runtime_check ? "⚠️ This appears to be a runtime/state error. Check database, API, and environment variables." : ""}
    `.trim();

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const exportMarkdown = () => {
    const markdown = `# Code Doctor Diagnosis

**Confidence:** ${result.confidence.toUpperCase()}  
**Crash Location:** \`${result.crash_node?.file}:${result.crash_node?.line}\`

## Root Cause Hypothesis

${result.root_cause_hypothesis}

${result.requires_runtime_check ? "> ⚠️ **Warning:** This appears to be a runtime/state error. Ensure you check database queries, API responses, and environment variables.\n" : ""}

## Fix Suggestions

${result.fix_suggestions.map((s, i) => `${i + 1}. ${s}`).join("\n")}

## Verification Steps

${result.verification_steps.map((s, i) => `${i + 1}. ${s}`).join("\n")}

---
*Generated by CodeAutopsy Code Doctor*
`;

    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `diagnosis-${Date.now()}.md`;
    a.click();
    URL.revokeObjectURL(url);
  };

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      animate={{ opacity: 1, y: 0 }}
      className="space-y-6"
    >
      {/* Header with Actions */}
      <div className="flex items-center justify-between flex-wrap gap-4">
        <div className="flex items-center gap-3">
          <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-blue-500/20 to-indigo-500/20 border border-blue-500/30 flex items-center justify-center">
            <span className="text-2xl">🩺</span>
          </div>
          <div>
            <h3 className="text-lg font-bold text-white">Code Doctor Diagnosis</h3>
            <div className={`inline-flex items-center gap-2 px-3 py-1 rounded-lg text-xs font-bold uppercase tracking-wider border ${confidenceColors[result.confidence]}`}>
              {result.confidence} Confidence
            </div>
          </div>
        </div>

        <div className="flex items-center gap-2">
          {/* Copy Button */}
          <button
            onClick={copyDiagnosis}
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm"
          >
            {copied ? <Check className="w-4 h-4" /> : <Copy className="w-4 h-4" />}
            {copied ? "Copied!" : "Copy"}
          </button>

          {/* Export Button */}
          <button
            onClick={exportMarkdown}
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm"
          >
            <Download className="w-4 h-4" />
            Export
          </button>

          {/* Reset Button */}
          <button
            onClick={onReset}
            className="px-4 py-2 rounded-lg bg-white/5 hover:bg-white/10 border border-white/10 text-slate-300 hover:text-white transition-all flex items-center gap-2 text-sm"
          >
            <RotateCcw className="w-4 h-4" />
            New Diagnosis
          </button>
        </div>
      </div>

      {/* Runtime Check Warning */}
      {result.requires_runtime_check && (
        <div className="p-4 rounded-xl bg-yellow-500/10 border border-yellow-500/20 flex items-start gap-3">
          <span className="text-xl">⚠️</span>
          <div className="flex-1">
            <p className="text-sm text-yellow-200 font-medium mb-1">
              This appears to be a state or data error.
            </p>
            <p className="text-xs text-yellow-300/70">
              Ensure you check your database, API endpoints, and environment variables.
            </p>
          </div>
        </div>
      )}

      {/* Root Cause */}
      <div className="p-6 rounded-xl bg-white/[0.02] border border-white/10">
        <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-3">
          Root Cause Hypothesis
        </h4>
        <p className="text-slate-200 leading-relaxed">
          {result.root_cause_hypothesis}
        </p>
      </div>

      {/* Fix Suggestions */}
      <div className="p-6 rounded-xl bg-white/[0.02] border border-white/10">
        <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4">
          Fix Suggestions
        </h4>
        <div className="space-y-3">
          {result.fix_suggestions.map((suggestion, i) => (
            <div key={i} className="flex gap-3">
              <div className="w-6 h-6 rounded-full bg-blue-500/20 border border-blue-500/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="text-xs text-blue-300 font-bold">{i + 1}</span>
              </div>
              <p className="text-sm text-slate-300 leading-relaxed">{suggestion}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Verification Steps */}
      <div className="p-6 rounded-xl bg-white/[0.02] border border-white/10">
        <h4 className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-4">
          Verification Steps
        </h4>
        <div className="space-y-3">
          {result.verification_steps.map((step, i) => (
            <div key={i} className="flex gap-3">
              <div className="w-6 h-6 rounded-full bg-green-500/20 border border-green-500/30 flex items-center justify-center flex-shrink-0 mt-0.5">
                <span className="text-xs text-green-300 font-bold">{i + 1}</span>
              </div>
              <p className="text-sm text-slate-300 leading-relaxed">{step}</p>
            </div>
          ))}
        </div>
      </div>

      {/* Feedback */}
      <div className="flex items-center justify-center gap-4 pt-4 pb-2">
        <span className="text-xs text-slate-500 uppercase tracking-wider">
          Was this helpful?
        </span>
        <div className="flex gap-2">
          <button
            onClick={() => setFeedback("up")}
            className={`p-2 rounded-lg border transition-all ${
              feedback === "up"
                ? "bg-green-500/20 border-green-500/40 text-green-400"
                : "bg-white/5 border-white/10 text-slate-400 hover:text-green-400"
            }`}
          >
            <ThumbsUp className="w-4 h-4" />
          </button>
          <button
            onClick={() => setFeedback("down")}
            className={`p-2 rounded-lg border transition-all ${
              feedback === "down"
                ? "bg-red-500/20 border-red-500/40 text-red-400"
                : "bg-white/5 border-white/10 text-slate-400 hover:text-red-400"
            }`}
          >
            <ThumbsDown className="w-4 h-4" />
          </button>
        </div>
      </div>
    </motion.div>
  );
}